name: Run Subfinder

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-subfinder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Cache Subfinder
        uses: actions/cache@v3
        with:
          path: ~/.subfinder
          key: subfinder-v2.5.7
          restore-keys: |
            subfinder-

      - name: Install Subfinder (if not cached)
        run: |
            wget https://github.com/projectdiscovery/subfinder/releases/download/v2.5.7/subfinder_2.5.7_linux_amd64.zip
            unzip subfinder_2.5.7_linux_amd64.zip -d ~/.subfinder
            sudo mv ~/.subfinder/subfinder /usr/local/bin/
      - name: Run Subfinder
        run: |
          subfinder -d example.com -o results.txt
          cat results.txt

      - name: Upload Results
        uses: actions/upload-artifact@v3
        with:
          name: subfinder-results
          path: subs
