name: Run Subfinder

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-subfinder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Subfinder
        run: |
          sudo apt update
          sudo apt install -y wget
          wget https://github.com/projectdiscovery/subfinder/releases/download/v2.5.7/subfinder_2.5.7_linux_amd64.zip
          unzip subfinder_2.5.7_linux_amd64.zip
          sudo mv subfinder /usr/local/bin/
          subfinder -version

      - name: Run Subfinder
        run: |
          subfinder -d example.com -o results.txt
          cat results.txt

      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: subfinder-results
          path: results.txt
