name: Bug Hunting

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-subfinder:
    runs-on: ubuntu-latest

    env:
      TARGET_DOMAIN: nubank.com.br  # Change this to your target domain

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Tools
        run: |
          sudo apt update
          sudo apt install -y wget unzip python3-pip

          # Install Subfinder
          wget https://github.com/projectdiscovery/subfinder/releases/download/v2.5.7/subfinder_2.5.7_linux_amd64.zip
          unzip -o subfinder_2.5.7_linux_amd64.zip
          sudo mv subfinder /usr/local/bin/
          sudo subfinder -up        

          # Install Httpx
          wget https://github.com/projectdiscovery/httpx/releases/download/v1.6.10/httpx_1.6.10_linux_amd64.zip
          unzip -o httpx_1.6.10_linux_amd64.zip
          sudo mv httpx /usr/local/bin
          sudo httpx -up

          # Install Nuclei
          wget https://github.com/projectdiscovery/nuclei/releases/download/v3.3.9/nuclei_3.3.9_linux_amd64.zip
          unzip -o nuclei_3.3.9_linux_amd64.zip
          sudo mv nuclei /usr/local/bin
          sudo nuclei -up

          # Install wafw00f with fix
          sudo apt install -y python3-setuptools python3-wheel
          git clone https://github.com/EnableSecurity/wafw00f.git
          cd wafw00f
          sudo pip3 install .
          cd ..

          # Install Katana
          wget https://github.com/projectdiscovery/katana/releases/download/v1.1.2/katana_1.1.2_linux_amd64.zip
          unzip -o katana_1.1.2_linux_amd64.zip
          sudo mv katana /usr/local/bin
          sudo katana -up

      - name: Run Subfinder and Tools
        run: |
          subfinder -d ${{ env.TARGET_DOMAIN }} -all -recursive -silent -o subs.txt
          cat subs.txt | httpx -td -title -sc -ip -cdn -o live_host.txt
          cat live_host.txt | awk '{print $1}' | tee live_subs.txt
          nuclei -l live_subs.txt -rl 10 -bs 2 -c 2 -as -s critical,high,medium -o nuclei_results.txt
          cat live_subs.txt | xargs -I {} wafw00f -v {} | tee waf_detection.txt
          cat live_host.txt | grep 403 | awk '{print $1}' | tee forbidden_hosts.txt
          katana -list live_subs.txt -o urls.txt

      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: scan result
          path: |
            subs.txt
            live_host.txt
            live_subs.txt
            nuclei_results.txt
            waf_detection.txt
            forbidden_hosts.txt
            urls.txt
